version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8088:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
  web1:
    build: ./web1
    expose:
      - "80"
  web2:
    build: ./web2
    expose:
      - "80"
